### ISSUE TITLE
你好，plato.pt下载不了，可以在提供一个下载链接吗？谢谢

### ISSUE THREAD

**Issue by Chunfeng1994** [HwwAncient/Pytorch-PLATO#3]

**Comment by HwwAncient** [comment]
We have already offered the download link in the README.md

<img width="807" alt="image" src="https://user-images.githubusercontent.com/38929139/183828895-4bc00c9f-15a7-4c05-9039-698c7cc718ef.png">

**Comment by Chunfeng1994** [comment]
你好，这个链接点不进去啊，提示网址失效

**Comment by HwwAncient** [comment]
I could download it. The model file is placed on Google Drive, so you may use VPN to get it.

**Comment by Chunfeng1994** [comment]
好的，谢谢
